# Generated by Django 3.0.7 on 2020-12-05 07:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('1', 'Electronic'), ('2', 'Clothes'), ('3', 'Beauty'), ('4', 'Phone Cases')], max_length=20)),
                ('price', models.IntegerField()),
                ('description', models.TextField(max_length=250)),
            ],
        ),
    ]
