# Generated by Django 3.0.7 on 2020-12-07 06:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_auto_20201206_0815'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='kind',
            field=models.CharField(choices=[('1', 'Electronic'), ('2', 'Furniture'), ('3', 'Bedroom'), ('4', 'Dining')], max_length=30),
        ),
    ]
